name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Build app
      run: |
        pip install pyinstaller
        pyinstaller --noconfirm --onefile --name copy.exe main.py
        python -c "file=open('dist/copy.exe', 'rb');open('bin/copy.exe', 'wb').write(file.read())"
        cmd /c "rmdir dist /s /Q"
        cmd /c "rmdir build /s /Q"
        cmd /c "del copy.spec /Q"
        
